######### run with: docker-compose up --build #########

version: '3.3'

networks:
  payment-channel:


services:
    # dappflow sandbox expects the following:
    # Algod url: http://localhost
    # Algod port: 4001
    # Algod token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    # Indexer url: http://localhost
    # Indexer port: 8980
    # Indexer token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  algorand-algod:
    container_name: "algorand-algod"
    build:
      context: .
      dockerfile: ./images/algod/Dockerfile
      args:
        CHANNEL: "${ALGOD_CHANNEL:-stable}"
        URL: "${ALGOD_URL}"
        BRANCH: "${ALGOD_BRANCH}"
        SHA: "${ALGOD_SHA}"
        BOOTSTRAP_URL: "${NETWORK_BOOTSTRAP_URL}"
        GENESIS_FILE: "${NETWORK_GENESIS_FILE}"
        TEMPLATE: "${NETWORK_TEMPLATE:-images/algod/template.json}"
        NETWORK_NUM_ROUNDS: "${NETWORK_NUM_ROUNDS:-300000}"
        NODE_ARCHIVAL: "${NODE_ARCHIVAL}"
        TOKEN: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        ALGOD_PORT: "4001"
        KMD_PORT: "4002"
        CDT_PORT: "9392"
    networks:
      - payment-channel
    ports:
      - ${ALGOD_PORT:-4001}:4001
      - ${KMD_PORT:-4002}:4002
      - ${CDT_PORT:-9392}:9392

  algorand-indexer:
    container_name: "algorand-indexer"
    build:
      context: .
      dockerfile: ./images/indexer/Dockerfile
      args:
        URL: "${INDEXER_URL:-https://github.com/algorand/indexer}"
        BRANCH: "${INDEXER_BRANCH:-master}"
        SHA: "${INDEXER_SHA}"
    networks:
      - payment-channel
    ports:
      - ${INDEXER_PORT:-8980}:8980
    restart: unless-stopped
    environment:
      DISABLED: "${INDEXER_DISABLED}"
      PORT: "8980"
      SNAPSHOT: ""
      CONNECTION_STRING: "host=algorand-indexer-db port=5432 user=algorand password=algorand dbname=indexer_db sslmode=disable"
      ALGOD_ADDR: "algorand-algod:4001"
      ALGOD_TOKEN: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
      INDEXER_ENABLE_ALL_PARAMETERS: "${INDEXER_ENABLE_ALL_PARAMETERS:-false}"
    depends_on:
      - algorand-indexer-db
      - algorand-algod

  algorand-indexer-db:
    container_name: "algorand-indexer-db"
    image: "postgres:13-alpine"
    networks:
      - payment-channel
    ports:
      - ${POSTGRES_PORT:-5433}:5432
    user: postgres
    environment:
      POSTGRES_USER: algorand
      POSTGRES_PASSWORD: algorand
      POSTGRES_DB: indexer_db

  asc-alice:
    container_name: "asc-alice"
    build: 
      context: .
    networks:
      - payment-channel
    expose:
      - "28547"
    # environment:
      # SEED_PHRASE: "auction palm thumb shuffle aim fade cover glass fire spawn course harbor moon decline shed shop envelope virtual visa attitude hand december portion abstract labor"

  asc-bob:
    container_name: "asc-bob"
    build: 
      context: .
    networks:
      - payment-channel
    expose:
      - "28547"
    # environment:
    #   SEED_PHRASE: "prize struggle destroy tray harvest wear century length thought diagram rubber page bridge weasel same ocean team index skin volume witness record cinnamon able machine"